database:
  build: ./mysql
  restart: always
  ports:
    - "3306:3306"
  volumes:
    - ./data:/var/lib/mysql
    - ./mysql/conf/mysql.cnf:/etc/mysql/my.cnf
    - ./db-seeds:/docker-entrypoint-initdb.d/
  environment: { MYSQL_DATABASE: www, MYSQL_USER: www, MYSQL_PASSWORD: www, MYSQL_ALLOW_EMPTY_PASSWORD: 'yes', MYSQL_ROOT_PASSWORD: 'root' }
