web:
  build: ./web
  restart: always
  ports:
    - "80:80"
    - "443:443"
  links:
    - database
    - memcache
    - mailhog
  volumes:
    - ./www:/var/www/html
  environment: { VIRTUAL_HOST: www.oist.dev, PLATFORM_DOCKER: www }
database:
  build: ./mysql
  restart: always
  ports:
    - "3306:3306"
  volumes:
    - ./data:/var/lib/mysql
    - ./db-seeds:/docker-entrypoint-initdb.d/
  environment: { MYSQL_DATABASE: www, MYSQL_USER: www, MYSQL_PASSWORD: www, MYSQL_ALLOW_EMPTY_PASSWORD: 'yes', MYSQL_ROOT_PASSWORD: 'root' }
memcache:
  image: bpressure/alpine-memcached:latest
  ports:
    - "11211:11211"
mailhog:
  image: mailhog/mailhog
  ports:
    - "8025:8025"
    - "1025:1025"
